### ISSUE TITLE
WS picker not showing all the simulations

### ISSUE THREAD

**Issue by DenoBeno** [crismaproject/wirecloud-widgets#2]
On Pilot C instance, checking the "Final Worldstates" in the ICMM world state picker settings results in a list of states finishing with 

Simulation 259: WS 2754
Simulation 269: WS 2852
Simulation 269: WS 2871
Simulation 269: WS 2872
Simulation 276: WS 2880 

The simulations 277-302 exist too, but aren't shown. I don't understand how the final WS is defined, but there should be some final WSs for these simulations runs.

Btw, there can be more than one "final WS" per simulation run. See e.g. simulation 286.

**Comment by MrManny** [comment]
Hm, I'm not 100% sure what you are saying. Can you elaborate?

If the option "show all simulation runs" is un-checked, it will only show leaf worldstates, ie. worldstates without any children (leaves of a worldstate tree), which is any worldstate on the ICMM with an empty childworldstates array.
