### ISSUE TITLE
Missing output on Indicators widget

### ISSUE THREAD

**Issue by DenoBeno** [crismaproject/wirecloud-widgets#3]
It would be convenient if our widgets and those of cismet would talk to each other. 

In particular, it woudl be good to analyse the WSs which are selected in the "indicators" widget in the cismets ws analysis widget. The problem is that the output of indicators widget isn't compatible with the input of cismets analysis widget.

**Comment by MrManny** [comment]
Is this about ./indicators or ./IndicatorsViewer? The former has no use in pilot C and is thus not actively maintained, but I can look into it. The latter is maintained by Peter Kutschera and/or Maria Egly, I can forward them to this issue if requested.

**Comment by DenoBeno** [comment]
In fact, I just realized that our indicators viewer does not generate any output (tested with debugging "listener" widget). Maria has already seen it...

**Comment by eglym** [comment]
The IndicatorViewer widget has two output endpoints defined: "Selected Indicators" and "Selected World States". Currently, the endpoint "Selected Indicators" is set when the timeline is displayed and the user selects one of the time-interval indicators, if they are defined as selectable by the "Indicator Filter" input endpoint. This is used in Pilot E v1 (the Exercise Support Application) for the communication between the different indicator widgets. "Selected World States" output endpoint is currently not set at all. If there is a requirement to do so, please specify what you exactly expect from this endpoint - then we can implement it accordingly.

**Comment by DenoBeno** [comment]
What I would expect is to be able to connect the output of this widget to input of multi-criteria widget. In this way, one could choose the simulation then choose one or more WSs from this simulation and then compare them using multi-criteria widget. Or any other widget that is able to visualize data.
