### ISSUE TITLE
Multiselect and indicators widget?

### ISSUE THREAD

**Issue by DenoBeno** [crismaproject/wirecloud-widgets#4]
In order to use the indicators widget with cismet ws analysis widget, it would be convenient if one could select several input world states and present these as several WS trees in the indicators widget.

**Comment by MrManny** [comment]
Is this about ./indicators or ./IndicatorsViewer? The former has no use in pilot C and is thus not actively maintained, but I can look into it. The latter is maintained by Peter Kutschera and/or Maria Egly, I can forward them to this issue if requested.

**Comment by eglym** [comment]
This is about IndicatorViewer. If it is essential for the project result, we can put it onto the change request list we already have got for Pilot C.
